name: Realease and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cach Gradle
        uses: actions/cach
        with:
          path: | 
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}

      - name: Build e testes
        run: ./gradlew clean build

      - name: Gerar versão
        id: version
        run: |
          VERSION=v$(date +'%Y.%m.%d.%H%M')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Criar Release
        uses: softprops/action-gh-release
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          generate_release_notes: true

      - name: Deploy na Render
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"